name: agbero

services:
  setup:
    image: python:3.12-slim
    volumes:
      - .:/app:rw
    working_dir: /app
    command: >
      bash -c "apt-get update &&
      apt-get install -y gcc libpq-dev &&
      python -m venv .venv &&
      . .venv/bin/activate &&
      pip install -r requirements.txt"
    restart: "no"

  api:
    image: python:3.12-slim
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "apt-get update &&
      apt-get install -y libpq-dev &&
      . .venv/bin/activate &&
      python3 main.py"
    depends_on:
      postgres:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    restart: "unless-stopped"

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "unless-stopped"

volumes:
  postgres_data:
