name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: cd-production
  cancel-in-progress: true

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment:
      name: "production"

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd agbero/backend
            git fetch origin main
            git reset --hard origin/main
            docker compose down
            docker compose up -d

  deploy-frontend:
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ vars.URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Create env file
        working-directory: ./frontend
        run: echo "${{ secrets.ENV_FILE }}" | base64 -d > .env

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build the application
        working-directory: ./frontend
        run: npm run build

      - name: Deploy on Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "frontend/dist/"
          strip_components: 2
          target: /var/www/agbero
