name: Continuous Deployment

on:
  push:
    branches:
      - main

concurrency:
    group: cd-production
    cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ vars.PROD_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd agbero

            git fetch origin main
            git reset --hard origin/main

            docker-compose down
            docker-compose up -d
